### ISSUE TITLE
error running Gulp: "bundle() no longer accepts option arguments."

### ISSUE THREAD

**Issue by garyrob** [redbadger/react-isomorphic#2]
Here's the complete error I get after installing everything:

garyrob$ gulp
[15:53:56] Using gulpfile ~/Source/test/react-isomorphic/node_modules/react-isomorphic/gulpfile.js
[15:53:56] Starting 'copy-scripts'...
[15:53:56] Starting 'styles'...
[15:53:56] Starting 'browserify'...
[15:53:56] Bundling
[15:53:56] 'browserify' errored after 15 ms
[15:53:56] Error: bundle() no longer accepts option arguments.
Move all option arguments to the browserify() constructor.
    at Browserify.bundle (/usr/local/lib/node_modules/browserify/index.js:702:15)
    at update (/Users/garyrob/Source/test/isomorphic-react/node_modules/react-isomorphic/gulpfile.ls:37:18)
    at Gulp.<anonymous> (/Users/garyrob/Source/test/isomorphic-react/node_modules/react-isomorphic/gulpfile.ls:42:10)
    at module.exports (/Users/garyrob/Source/test/isomorphic-react/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/garyrob/Source/test/isomorphic-react/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/garyrob/Source/test/isomorphic-react/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/garyrob/Source/test/isomorphic-react/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
[15:53:56] Finished 'copy-scripts' after 55 ms
[15:53:56] Finished 'styles' after 48 ms

**Comment by robbiemccorkell** [comment]
Hi @garyrob, sorry it took so long to look at this. The pull request above should fix it.
